version: '3.8'

services:
  backend:
    env_file:
      - ./.env
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL="postgresql://user:password@postgres:5432/dashline?schema=public"
      - POSTGRES_USER='user'
      - POSTGRES_PASSWORD='password'
      - POSTGRES_DB='dashline'
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    env_file:
      - ./.env
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:3000"
    environment:
      - VITE_API_URL='http://localhost:8080/api'
      - VITE_GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  postgres:
    image: postgres:13.5
    container_name: postgres
    environment:
      - POSTGRES_USER='user'
      - POSTGRES_PASSWORD='password'
      - POSTGRES_DB='dashline'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-h", "localhost"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s

volumes:
  postgres_data:
    driver: local
