version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3025:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3025/health"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3020:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3020/"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s

  postgres:
    image: postgres:13.5
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-h", "localhost"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s

volumes:
  postgres_data:
    driver: local
